// ==UserScript==
// @name     Destination Caps Highlighter
// @version  1.9
// @grant    none
// @include  *
// @updateURL   https://raw.githubusercontent.com/prateekmaddy/user_script/master/fdsc2.meta.js
// @downloadURL https://raw.githubusercontent.com/prateekmaddy/user_script/master/fdsc2.meta.js
// ==/UserScript==


 function highlightWord(word) {
    var xpath = "//text()[contains(., '" + word + "')]"; 
    var texts = document.evaluate(xpath, document.body, null, XPathResult.UNORDERED_NODE_SNAPSHOT_TYPE, null);
    for (n = 0; n < texts.snapshotLength; n++) {
        var textNode = texts.snapshotItem(n);
        var p = textNode.parentNode;
        var a = [];
        var frag = document.createDocumentFragment();
        textNode.nodeValue.split(word).forEach(function(text, i) {
            var node;
            if (i) {
                node = document.createElement('span');
                node.style.textDecoration = 'underline overline';
                              node.style.backgroundColor = 'Yellow';

                node.appendChild(document.createTextNode(word));
                frag.appendChild(node);
            }
            if (text.length) {
                frag.appendChild(document.createTextNode(text));
            }
            return a;
        });
        p.replaceChild(frag, textNode);
    }
}

highlightWord('ABE2->DEW1')
highlightWord('ABE2->DEW1')
highlightWord('ABE2->DEW1')
highlightWord('ABE2->DEW1')
highlightWord('ACY5->DEW8-CYC1')
highlightWord('ACY5->DPH2-CYC1')
highlightWord('ATL6->DAT1-CYC1')
highlightWord('ATL6->DAT2-CYC1')
highlightWord('ATL6->DAT3-CYC1')
highlightWord('ATL6->DBM2-CYC1')
highlightWord('BDL2->DBL1-A')
highlightWord('BDL2->DBO2-A')
highlightWord('BDL2->DBO3-A')
highlightWord('BDL2->DBO7-B')
highlightWord('BDL2->DRO1-B')
highlightWord('BDL3->DBO7-B')
highlightWord('BDL5->DBL1-CYC1')
highlightWord('BFI3->DPD1-A')
highlightWord('BFI3->DSE2-A')
highlightWord('BFI3->DSE4-A')
highlightWord('BFI3->DSE5-A')
highlightWord('BFI3->DSE7-A')
highlightWord('BNA2->DIN1-B')
highlightWord('BNA2->DNA1-A')
highlightWord('BNA3->DNA1-A')
highlightWord('BOS5->DBO1-CYC1')
highlightWord('BOS5->DBO2-CYC1')
highlightWord('BOS5->DBO3-CYC1')
highlightWord('BOS5->DBO6-CYC1')
highlightWord('BOS5->DBO7-CYC1')
highlightWord('BOS5->DRI1-CYC1')
highlightWord('BOS7->DBL1-A')
highlightWord('BOS7->DBO1-A')
highlightWord('BOS7->DBO2-A')
highlightWord('BOS7->DBO3-A')
highlightWord('BOS7->DBO6-A')
highlightWord('BOS7->DBO7-B')
highlightWord('BUF5->DRO1-CYC1')
highlightWord('BWI5->DDC2-CYC1')
highlightWord('BWI5->DDC3-CYC1')
highlightWord('CAE1->DBM2-B')
highlightWord('CAE1->DRT1-B')
highlightWord('CLE2->DIN1-B')
highlightWord('CLE2->DPP1-A')
highlightWord('CLE3->DRO1-B')
highlightWord('CLE5->DCL1-CYC1')
highlightWord('CLE5->DCL2-CYC1')
highlightWord('CLT5->DSC2-CYC1')
highlightWord('CMH2->DIN1-B')
highlightWord('CMH3->DIN1-B')
highlightWord('CVG9->DCN1-CYC1')
highlightWord('CVG9->DKY2-CYC1')
highlightWord('DET1->DDT1-A')
highlightWord('DET1->DDT2-A')
highlightWord('DFW6->DDA1-A')
highlightWord('DFW8->DDA1-CYC1')
highlightWord('DTW1->DIN1-B')
highlightWord('DTW1->DRO1-B')
highlightWord('DTW5->DDT1-CYC1')
highlightWord('DTW5->DDT2-CYC1')
highlightWord('DTW5->DGR1-CYC1')
highlightWord('EWR4->DEW1')
highlightWord('EWR4->DEW1')
highlightWord('EWR4->DEW1')
highlightWord('EWR4->DEW1')
highlightWord('EWR4->DRO1-B')
highlightWord('EWR5->DEW1-CYC1')
highlightWord('EWR5->DEW1-CYC1')
highlightWord('EWR5->DEW1-CYC1')
highlightWord('EWR5->DEW1-CYC1')
highlightWord('EWR5->DNY4-CYC1')
highlightWord('EWR5->DNY4-CYC1')
highlightWord('EWR5->DNY4-CYC1')
highlightWord('EWR5->DNY4-CYC1')
highlightWord('EWR8->DEW1')
highlightWord('EWR8->DEW2-CYC1')
highlightWord('EWR8->DEW2-CYC1')
highlightWord('EWR8->DEW2-CYC1')
highlightWord('EWR8->DEW2-CYC1')
highlightWord('EWR8->DEW2-CYC1')
highlightWord('EWR8->DEW2-CYC1')
highlightWord('EWR8->DEW2-CYC1')
highlightWord('EWR8->DEW2-CYC1')
highlightWord('EWR8->DEW2-CYC1')
highlightWord('EWR8->DNY4-CYC1')
highlightWord('EWR8->DNY4-CYC1')
highlightWord('EWR8->DNY4-CYC1')
highlightWord('EWR8->DNY4-CYC1')
highlightWord('FAT1->DSF3-A')
highlightWord('FAT1->DSF4-A')
highlightWord('FAT1->DSF5-A')
highlightWord('FAT1->DSM1-A')
highlightWord('HOU1->DHO1-CYC1')
highlightWord('HOU1->DHO4-CYC1')
highlightWord('HOU3->DHO1-A')
highlightWord('IND1->DIN1-A')
highlightWord('IND1->DLI1-B')
highlightWord('JAX2->DFL1-A')
highlightWord('JAX2->DGE2-A')
highlightWord('JAX2->DJX1-A')
highlightWord('JAX2->DSC2-A')
highlightWord('JAX3->DJX1-A')
highlightWord('JAX5->DFL1-CYC1')
highlightWord('JAX5->DGE2-CYC1')
highlightWord('JAX5->DJX1-CYC1')
highlightWord('JFK8->DEW1')
highlightWord('JFK8->DEW1')
highlightWord('JFK8->DEW1')
highlightWord('JFK8->DEW1')
highlightWord('JFK8->DRI1-A')
highlightWord('LAS7->DLV1-A')
highlightWord('LGA9->DEW1')
highlightWord('LGA9->DEW1')
highlightWord('LGA9->DEW1')
highlightWord('LGA9->DEW1')
highlightWord('LGB3->DLV1-A')
highlightWord('MCI5->DMC1-CYC1')
highlightWord('MCI5->DOM1-CYC1')
highlightWord('MCO1->DFL1-A')
highlightWord('MCO1->DMO3-B')
highlightWord('MCO5->DMO1-CYC1')
highlightWord('MCO5->DMO3-CYC1')
highlightWord('MCO5->DSR1-CYC1')
highlightWord('MCO5->DTP2-CYC1')
highlightWord('MCO9->DMO1-CYC1')
highlightWord('MCO9->DMO3-CYC1')
highlightWord('MCO9->DSR1-CYC1')
highlightWord('MCO9->DTP2-CYC1')
highlightWord('MDT1->DDC4-A')
highlightWord('MDW5->DCH3-CYC1')
highlightWord('MDW5->DCH5-CYC1')
highlightWord('MDW5->DCH7-CYC1')
highlightWord('MDW5->DIL1-CYC1')
highlightWord('MEM5->DLR1-CYC1')
highlightWord('MGE5->DAT1-CYC1')
highlightWord('MGE5->DAT2-CYC1')
highlightWord('MGE5->DAT3-CYC1')
highlightWord('MKC4->DMC1-A')
highlightWord('MKC6->DLI1-B')
highlightWord('MKC6->DOM1-A')
highlightWord('MKE5->DCH5-CYC1')
highlightWord('MKE5->DML2-CYC1')
highlightWord('MOB5->DLB1-CYC1')
highlightWord('MOB5->DNO1-CYC1')
highlightWord('MSP1->DMS1-A')
highlightWord('OAK4->DSF3-A')
highlightWord('OAK4->DSF4-A')
highlightWord('OAK4->DSF5-A')
highlightWord('OAK4->DSM1-A')
highlightWord('ONT2->DLV1-A')
highlightWord('PDX5->DID2-CYC1')
highlightWord('PDX7->DPD1-A')
highlightWord('PHX5->DPX3-A')
highlightWord('PIT5->DPP1-CYC1')
highlightWord('PNE5->DEW2-CYC1')
highlightWord('PNE5->DEW2-CYC1')
highlightWord('PNE5->DEW2-CYC1')
highlightWord('PNE5->DEW2-CYC1')
highlightWord('PNE5->DEW4-CYC1')
highlightWord('PNE5->DEW8-CYC1')
highlightWord('PNE5->DPH1-CYC1')
highlightWord('PNE5->DPH2-CYC1')
highlightWord('PNE5->DPH6-CYC1')
highlightWord('RDU5->DRT1-CYC1')
highlightWord('RIC1->DOR1-A')
highlightWord('RIC1->DRT1-B')
highlightWord('RIC5->DDC4-CYC1')
highlightWord('RIC5->DOR1-CYC1')
highlightWord('SDF8->DCH3-B')
highlightWord('SLC1->DUT1-A')
highlightWord('SMF1->DSM1-A')
highlightWord('STL4->DLI1-A')
highlightWord('STL5->DLI1-CYC1')
highlightWord('TPA1->DFL1-A')
highlightWord('TPA1->DSR1-A')
highlightWord('TPA2->DMO3-B')
highlightWord('TPA2->DTP2-A')
highlightWord('LGA9->BDL5')
highlightWord('LGA9->BDL5')
highlightWord('LGA9->BDL5')
highlightWord('LGA9->BDL5')
highlightWord('PDX9->PDX5-CART-A')
